- name: Update and upgrade apt packages
  become: true
  check_mode: false
  changed_when: false
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400 # One day, only updates if caches are older than this.
    autoremove: true

- name: apt install standard utilities and packages
  become: true
  apt:
    state: present
    name:
      - fail2ban
      - htop
      - iftop
      - net-tools
      - unattended-upgrades
      - unzip
