---
- name: Install nginx
  become: true
  ansible.builtin.apt:
    name: nginx
    state: present

- name: Remove default nginx site
  become: true
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: Reload_nginx

- name: Deploy nginx vhost config
  become: true
  ansible.builtin.template:
    src: dice.triplea-game.org.conf.j2
    dest: /etc/nginx/sites-available/dice.triplea-game.org.conf
    owner: root
    group: root
    mode: "0644"
  notify: Reload_nginx

- name: Enable nginx vhost
  become: true
  ansible.builtin.file:
    src: /etc/nginx/sites-available/dice.triplea-game.org.conf
    dest: /etc/nginx/sites-enabled/dice.triplea-game.org.conf
    state: link
  notify: Reload_nginx

- name: Open firewall port 80
  become: true
  community.general.ufw:
    rule: allow
    port: "80"
    proto: tcp

- name: Open firewall port 443
  become: true
  community.general.ufw:
    rule: allow
    port: "443"
    proto: tcp

- name: Ensure nginx is started and enabled
  become: true
  ansible.builtin.systemd:
    name: nginx
    state: started
    enabled: true
