---
- name: Create lobby group
  become: true
  ansible.builtin.group:
    name: lobby
    state: present

- name: Create lobby user
  become: true
  ansible.builtin.user:
    name: lobby
    group: lobby
    groups: docker
    state: present
    system: true
    create_home: false

- name: Create lobby working directory
  become: true
  ansible.builtin.file:
    state: directory
    mode: "0755"
    owner: lobby
    group: lobby
    path: "{{ lobby_working_directory }}"

- name: Deploy docker-compose.yml
  become: true
  notify: Restart_lobby
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ lobby_working_directory }}/docker-compose.yml"
    mode: "0644"
    owner: lobby
    group: lobby

- name: Deploy .env
  become: true
  notify: Restart_lobby
  ansible.builtin.template:
    src: .env.j2
    dest: "{{ lobby_working_directory }}/.env"
    mode: "0600"
    owner: lobby
    group: lobby

- name: Deploy lobby systemd service
  become: true
  notify: Restart_lobby
  ansible.builtin.template:
    src: lobby.service.j2
    dest: /etc/systemd/system/lobby.service
    owner: root
    group: root
    mode: "0644"

- name: Daemon-reload, enable and start the lobby service
  become: true
  ansible.builtin.systemd_service:
    daemon_reload: true
    name: lobby.service
    enabled: true
    state: started

- name: Configure user for CICD deployments - user named 'deploy'
  block:
    - name: Deploy script deploy-lobby.sh
      become: true
      ansible.builtin.template:
        src: deploy-lobby.sh.j2
        dest: "{{ lobby_working_directory }}/deploy-lobby.sh"
        owner: lobby
        group: lobby
        mode: "0755"

    - name: Deploy sudoers entry for deploy user - /etc/sudoers.d/deploy-lobby
      become: true
      ansible.builtin.template:
        src: deploy-lobby-sudoers.j2
        dest: /etc/sudoers.d/deploy-lobby
        owner: root
        group: root
        mode: "0440"
        validate: /usr/sbin/visudo -cf %s
