- name: assert variables are set
  assert:
    that:
      - server_name is defined

- name: create dir /etc/nginx/include/
  become: true
  file:
    path: /etc/nginx/include/
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: install nginx config to /etc/nginx/include/
  become: true
  notify: reload_nginx
  template:
    src: "{{ item.src }}"
    dest: /etc/nginx/include/{{ item.target }}
    mode: "0644"
    owner: root
    group: root
  with_items:
    - src: pre-server-lobby.conf
      target: pre-server-lobby.conf
    - src: server-lobby-2-7.conf
      target: server-lobby-2-7.conf
