- name: create backup-users group
  become: true
  group:
    name: backup-users
    state: present

# backup user is an account on the machine receiving the backups
# we deploy a public SSH key to the backup machine allowing
# the account to rsync files over
- name: create backup user
  become: true
  user:
    name: "{{ item }}"
    group: backup-users
    shell: /bin/bash
    state: present
  loop:
    - forums-backup

- name: add admin users to backup-users group
  become: true
  user:
    name: "{{ item }}"
    group: backup-users
    append: yes
  loop:
    - "{{ admin_users | map(attribute='name') | list }}"

- name: deploy forums-backup ssh public key to authorized_keys
  become: true
  authorized_key:
    user: forums-backup
    state: present
    exclusive: true
    key: "{{ lookup('file', role_path + '/files/forums-backup-public-keys') }}"

- name: create backups directory
  become: true
  file:
      state: directory
      path: /opt/backups/forums
      mode: "0770"
      owner: root
      group: backup-users

- name: prune old forum backup archives
  become: true
  cron:
    name: prune-forums-backups
    user: root
    hour: "8"
    minute: "0"
    job: find /opt/backups/forums -name "*.gz" -mtime +10 -delete
