# These variables are used across multiple roles.
# Other than these variables, roles should be fully self-contained.

ansible_connection: ssh
admin_group: admin
ansible_python_interpreter: /usr/bin/python3

