- name: ensure admin user group & docker user group exist
  become: true
  group:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ admin_group }}"
    - docker

- name: create admin user groups
  become: true
  group:
    name: "{{ item.name }}"
  with_items: "{{ admin_users }}"
  loop_control:
    label: "{{ item.name }}"

- name: create admin user accounts
  become: true
  user:
    name: "{{ item.name }}"
    shell: /bin/bash
    create_home: yes
    append: yes
    groups: "{{ item.name }},{{ admin_group }},docker"
  with_items: "{{ admin_users }}"
  loop_control:
    label: "{{ item.name }}"

- name: Deployer sudo permissions file - /etc/sudoers.d/[admin-user]
  become: true
  template:
    src: sudoer_file.sudo
    dest: "/etc/sudoers.d/{{ item.name }}"
    owner: root
    group: root
    mode: "0440"
  with_items: "{{ admin_users }}"
  loop_control:
    label: "{{ item.name }}"

- name: SSH keys - add authorized keys for admin users
  become: true
  authorized_key:
    user: "{{ item.0.name }}"
    key: "{{ item.1 }}"
    state: present
  loop: "{{ admin_users | subelements('ssh_keys') }}"
  loop_control:
    label: "{{ item.0.name }}"

# Deploy service account - limited to docker pull and service restarts only
- name: create user for deployment named 'deploy'
  block:
    - name: deploy user - create group
      become: true
      group:
        name: "{{ deploy_user.name }}"
        state: present

    - name: deploy user - create account
      become: true
      user:
        name: "{{ deploy_user.name }}"
        shell: /bin/bash
        create_home: yes
        groups: "{{ deploy_user.name }}"
        append: yes

    - name: deploy user - sudoers file
      become: true
      template:
        src: deploy_sudoer_file.sudo
        dest: "/etc/sudoers.d/{{ deploy_user.name }}"
        owner: root
        group: root
        mode: "0440"

    - name: deploy user - SSH directory
      become: true
      file:
        path: "/home/{{ deploy_user.name }}/.ssh/"
        state: directory
        mode: "700"
        owner: "{{ deploy_user.name }}"
        group: "{{ deploy_user.name }}"

    - name: deploy user - authorized_keys
      become: true
      authorized_key:
        user: "{{ deploy_user.name }}"
        state: present
        key: "{{ deploy_user.ssh_key }}"

