- hosts: all
  tags: system
  environment:
    DEBIAN_FRONTEND: noninteractive
    NEEDRESTART_MODE: a
  roles:
    - name: system/admin_user
      vars:
        admin_users: "{{ lookup('file', playbook_dir + '/../terraform/keys/admins.json') | from_json }}"
    - name: system/apt_packages
      tags: apt
    - system/docker
    - system/firewall
    - system/journald
    - system/logging_config
    # because hostname role may reboot the system, it is executed last. On reboot, any major package updates
    # will take effect & the system will be in a clean/ready state for further host-specific deployments.
    - system/hostname

- hosts: bots
  tags: [ bots, bot ]
  roles:
    - bot

# support uses the NGINX on the lobby host for reverse proxy
- hosts: support
  tags: support
  roles:
    - support/service
    - support/db_backup

- hosts: lobby
  tags: lobby
  roles:
    - {name: nginx, tags: nginx}
    - lobby/nginx_conf
    - support/nginx_conf
    - lobby/service
    - lobby/db_backup

- hosts: forums
  tags: forums
  roles:
    - forums

- hosts: marti
  tags: marti
  roles:
    # note: this marti/nginx_conf is not like the lobby or support server, it's a full standalone NGINX config
    - marti/nginx_conf
    - marti/service

