- hosts: all
  tags: system
  environment:
    DEBIAN_FRONTEND: noninteractive
    NEEDRESTART_MODE: a
  roles:
    - name: system/admin_user
      vars:
        admin_users: "{{ lookup('file', playbook_dir + '/../terraform/keys/admins.json') | from_json }}"
    - name: system/apt_packages
      tags: apt
    - system/docker
    - system/firewall
    - system/journald
    - system/logging_config
    # because hostname role may reboot the system, it is executed last. On reboot, any major package updates
    # will take effect & the system will be in a clean/ready state for further host-specific deployments.
    - system/hostname

- hosts: bots
  tags: [ bots, bot ]
  roles:
    - bot

- hosts: lobby
  tags: lobby
  roles:
    ## Use the lobby to host backup files.
    - backups_host
    - {name: reverse_proxy/nginx, tags: nginx}
    - {name: database/postgres, tags: database}
    - smtp/postfix
    - lobby/nginx_conf
    - database/postgres_database
    - lobby/flyway_migrate
    - service_systemctl_conf

- hosts: forums
  tags: forums
  roles:
    - forums
